In [1]:
import torch
import torch.nn.functional as F
from torch.utils import data
from torchinfo import summary
import torch.nn as nn
import torch.optim as optim
import sys
import pandas as pd
import pickle
import numpy as np
from tqdm import tqdm
from datetime import datetime
import copy
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

In [2]:
import platform; print(platform.platform())

macOS-14.6-arm64-arm-64bit


In [3]:
df = pd.read_csv('/Users/jandh/Desktop/Old Desktop/od/1 quater/Project Lab/labelled_data_500.csv')

In [4]:
x = pd.to_datetime(df['date']).value_counts()
x.sort_index().index

DatetimeIndex(['2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04',
               '2021-06-07', '2021-06-08', '2021-06-09', '2021-06-10',
               '2021-06-11', '2021-06-15', '2021-06-16', '2021-06-17',
               '2021-06-18', '2021-06-21', '2021-06-22'],
              dtype='datetime64[ns]', name='date', freq=None)

In [5]:
train_set = df[pd.to_datetime(df['date']) <= pd.to_datetime('2021-06-07')]
test_data = df[pd.to_datetime(df['date']) == pd.to_datetime('2021-06-08')]
train_set.head()

date      SP1   SV1      BP1  BV1      SP2   SV2      BP2   BV2  \
0  2021-06-01  10200.0  3294  10150.0   61  10250.0  2185  10100.0  1240   
1  2021-06-01  10200.0  3294  10150.0   59  10250.0  2185  10100.0  1240   
2  2021-06-01  10200.0  3324  10150.0   59  10250.0  2185  10100.0  1240   
3  2021-06-01  10200.0  3324  10150.0   43  10250.0  2185  10100.0  1240   
4  2021-06-01  10200.0  3324  10150.0   43  10250.0  2185  10100.0  1240   

       SP3  ...   BV3      SP4   SV4      BP4   BV4      SP5   SV5     BP5  \
0  10300.0  ...  1403  10350.0  2138  10000.0  2195  10400.0  2596  9990.0   
1  10300.0  ...  1403  10350.0  2138  10000.0  2195  10400.0  2596  9990.0   
2  10300.0  ...  1403  10350.0  2138  10000.0  2195  10400.0  2596  9990.0   
3  10300.0  ...  1403  10350.0  2138  10000.0  2195  10400.0  2596  9990.0   
4  10300.0  ...  1403  10350.0  2138  10000.0  2195  10400.0  2596  9990.0   

   BV5  label  
0  685      1  
1  685      1  
2  685      1  
3  685      1  
4  687      1  

[5 rows x 22 columns]

In [6]:
train_data =  train_set.iloc[:int(np.floor(train_set.shape[0] * 0.8)),:]
eval_data = train_set.iloc[int(np.floor(train_set.shape[0] * 0.8)):,:]

In [7]:
def normalize_data(df,cols,norm):
    #Normalizing using z-score
    if norm=='Z':
        scaler = StandardScaler()
        scaler.fit(df[cols])
        data = scaler.transform(df[cols])
    
    
    #Normalizing using DecPrec
    if norm=='DecPrec':
        k_len = np.ceil(np.log10(df[cols].abs().max()))
        # print(k_len)
        data = df[cols]/(10**k_len)

    return data,scaler

In [8]:
train_input , scaler = normalize_data(train_data.iloc[:,1:-1],train_data.iloc[:,1:-1].columns,'Z')
train_label = train_data.iloc[:,-1].to_numpy()
eval_input = scaler.transform(eval_data.iloc[:,1:-1])
eval_label = eval_data.iloc[:,-1].to_numpy()
test_input = scaler.transform(test_data.iloc[:,1:-1])
test_label = test_data.iloc[:,-1].to_numpy()

In [9]:
del [train_data,test_data,eval_data,df,train_set]

In [10]:
s=0
cc=0
key=0
obj=0
for key,obj in locals().items():
    cc= sys.getsizeof(obj)/1000000
    s+=cc
    if cc>20:
        print(key,cc)
print(s,'mb')

0.015896 mb


In [11]:
np.isnan(eval_input).any()

False

In [12]:
class Dataset_LOB(data.Dataset):
    """Characterizes a dataset for PyTorch"""
    def __init__(self, x,y, num_classes, T):
        """Initialization""" 
        # self.k = k
        self.num_classes = num_classes
        self.T = T
            
        # x = prepare_x(data)
        # y = get_label(data)
        x, y = data_classification(x, y, self.T)
        # y = y[:,self.k] - 1
        self.length = len(x)

        x = torch.from_numpy(x)
        self.x = torch.unsqueeze(x, 1)
        self.y = torch.from_numpy(y)

    def __len__(self):
        """Denotes the total number of samples"""
        return self.length

    def __getitem__(self, index):
        """Generates samples of data"""
        return self.x[index], self.y[index]

In [13]:
def data_classification(X, Y, T):
    [N, D] = X.shape
    # print(X.shape,T,N,Y.shape)
    df = np.array(X)
    # print(df.shape)
    dY = np.array(Y)

    dataY = dY[T - 1:N]

    dataX = np.zeros((N - T + 1, T, D))
    for i in range(T, N + 1):
        dataX[i - T] = df[i - T:i, :]

    return dataX, dataY


In [14]:
batch_size = 64
dataset_train = Dataset_LOB(train_input,train_label, num_classes=3, T=100)
dataset_eval = Dataset_LOB(eval_input,eval_label, num_classes=3, T=100)
dataset_test = Dataset_LOB(test_input,test_label, num_classes=3, T=100)

# test_loader = torch.utils.data.DataLoader(dataset=dataset_test, batch_size=batch_size, shuffle=False)

In [15]:
train_loader = torch.utils.data.DataLoader(dataset=dataset_train, batch_size=batch_size, shuffle=True)
val_loader = torch.utils.data.DataLoader(dataset=dataset_eval, batch_size=batch_size, shuffle=False)
test_loader = torch.utils.data.DataLoader(dataset=dataset_test, batch_size=batch_size, shuffle=False)
print(dataset_train.x.shape, dataset_test.y.shape)

torch.Size([1732671, 1, 100, 20]) torch.Size([282495])


In [16]:
tmp_loader = torch.utils.data.DataLoader(dataset=dataset_train, batch_size=1, shuffle=True)

for x, y in tmp_loader:
    print(x)
    print(y)
    print(x.shape, y.shape)
    break

tensor([[[[ 0.9308, -0.8022,  0.9326,  ..., -0.4754,  0.9477, -0.1733],
          [ 0.9308, -0.8022,  0.9326,  ..., -0.4754,  0.9477, -0.1733],
          [ 0.9308, -0.8022,  0.9326,  ..., -0.4754,  0.9477, -0.1733],
          ...,
          [ 0.9308, -0.7027,  0.9326,  ..., -0.5190,  0.9477, -0.1687],
          [ 0.9308, -0.7011,  0.9326,  ..., -0.5190,  0.9477, -0.1687],
          [ 0.9308, -0.7011,  0.9326,  ..., -0.5190,  0.9477, -0.1687]]]],
       dtype=torch.float64)
tensor([2])
torch.Size([1, 1, 100, 20]) torch.Size([1])


In [17]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

device = mps_device

tensor([1.], device='mps:0')


In [18]:
class deeplob(nn.Module):
    def __init__(self, y_len):
        super().__init__()
        self.y_len = y_len
        
        # convolution blocks
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=32, kernel_size=(1,2), stride=(1,2)),
            nn.LeakyReLU(negative_slope=0.01),
#             nn.Tanh(),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(32),
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(1,2), stride=(1,2)),
            nn.Tanh(),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.Tanh(),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.Tanh(),
            nn.BatchNorm2d(32),
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(1,5)),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(32),
            nn.Conv2d(in_channels=32, out_channels=32, kernel_size=(4,1)),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(32),
        )
        
        # inception moduels
        self.inp1 = nn.Sequential(
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=(1,1), padding='same'),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(64),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=(3,1), padding='same'),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(64),
        )
        self.inp2 = nn.Sequential(
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=(1,1), padding='same'),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(64),
            nn.Conv2d(in_channels=64, out_channels=64, kernel_size=(5,1), padding='same'),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(64),
        )
        self.inp3 = nn.Sequential(
            nn.MaxPool2d((3, 1), stride=(1, 1), padding=(1, 0)),
            nn.Conv2d(in_channels=32, out_channels=64, kernel_size=(1,1), padding='same'),
            nn.LeakyReLU(negative_slope=0.01),
            nn.BatchNorm2d(64),
        )
        
        # lstm layers
        self.lstm = nn.LSTM(input_size=192, hidden_size=64, num_layers=1, batch_first=True)
        self.fc1 = nn.Linear(64, self.y_len)

    def forward(self, x):
        # h0: (number of hidden layers, batch size, hidden size)
        h0 = torch.zeros(1, x.size(0), 64).to(device)
        c0 = torch.zeros(1, x.size(0), 64).to(device)
    
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        
        x_inp1 = self.inp1(x)
        x_inp2 = self.inp2(x)
        x_inp3 = self.inp3(x)  
        
        x = torch.cat((x_inp1, x_inp2, x_inp3), dim=1)
        
#         x = torch.transpose(x, 1, 2)
        x = x.permute(0, 2, 1, 3).contiguous()
        x = torch.reshape(x, (-1, x.shape[1], x.shape[2]))
        
        x, _ = self.lstm(x, (h0, c0))
        x = x[:, -1, :]
        x = self.fc1(x)
        forecast_y = torch.softmax(x, dim=1)
        
        return forecast_y

In [20]:
model = deeplob(y_len = dataset_train.num_classes)
model.to(mps_device)
# device = mps_device

deeplob(
  (conv1): Sequential(
    (0): Conv2d(1, 32, kernel_size=(1, 2), stride=(1, 2))
    (1): LeakyReLU(negative_slope=0.01)
    (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Conv2d(32, 32, kernel_size=(4, 1), stride=(1, 1))
    (4): LeakyReLU(negative_slope=0.01)
    (5): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): Conv2d(32, 32, kernel_size=(4, 1), stride=(1, 1))
    (7): LeakyReLU(negative_slope=0.01)
    (8): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (conv2): Sequential(
    (0): Conv2d(32, 32, kernel_size=(1, 2), stride=(1, 2))
    (1): Tanh()
    (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Conv2d(32, 32, kernel_size=(4, 1), stride=(1, 1))
    (4): Tanh()
    (5): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): Conv2d(32, 32, kernel_size=(4, 1), stride

In [23]:
class_count = Counter(train_label)
class_weights = torch.Tensor([len(train_label)/c for c in pd.Series(class_count).sort_index().values])
class_weights

tensor([15.6191,  1.1393, 17.1709])

In [24]:
class_weights[0]*=1.5
class_weights[2]*=1.5
class_weights

tensor([23.4287,  1.1393, 25.7564])

In [25]:
class_weights = class_weights.to(device)  
criterion = nn.CrossEntropyLoss(class_weights)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

In [26]:
class EarlyStopping:
    def __init__(self, patience=1, path='./model.pt'):
        self.patience = patience
        self.path= path
        self.counter = 0
        self.best_score = np.inf
        self.early_stop = False
        self.best_test_epoch = 0
        
    def __call__(self, val_loss, model,it):
        if self.best_score is None:
            self.best_score = val_loss
            self.save_checkpoint(model)
            self.best_test_epoch = it
    
        elif val_loss > self.best_score:
            self.counter +=1
            if self.counter >= self.patience:
                self.early_stop = True 
        else:
            self.best_score = val_loss
            self.save_checkpoint(model)
            self.counter = 0
            self.best_test_epoch = it

    def save_checkpoint(self, model):
        torch.save(model.state_dict(), self.path)

In [27]:
checkpoint_dir = '/Users/jandh/Desktop/Old Desktop/od/1 quater/Project Lab/fast-alphas/best_val_roLOB_oversampled.pt'

In [28]:
early_stopping = EarlyStopping(
        patience=7, 
        path=checkpoint_dir)

In [29]:
def batch_gd(model, criterion, optimizer, train_loader, test_loader, epochs):

    train_losses = np.zeros(epochs)
    test_losses = np.zeros(epochs)


    for it in tqdm(range(epochs)):
        
        model.train()
        t0 = datetime.now()
        train_loss = []
        for inputs, targets in train_loader:
            # move data to GPU
            inputs, targets = inputs.to(device, dtype=torch.float), targets.to(device, dtype=torch.int64)

            # zero the parameter gradients
            optimizer.zero_grad()
            # Forward pass
            # print("about to get model output")
            outputs = model(inputs)
            # print("done getting model output")
            # print("outputs.shape:", outputs.shape, "targets.shape:", targets.shape)
            loss = criterion(outputs, targets)
            # Backward and optimize
            # print("about to optimize")
            loss.backward()
            optimizer.step()
            train_loss.append(loss.item())
        # Get train loss and test loss
        train_loss = np.mean(train_loss) # a little misleading
    
        model.eval()
        test_loss = []
        for inputs, targets in test_loader:
            inputs, targets = inputs.to(device, dtype=torch.float), targets.to(device, dtype=torch.int64)      
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            test_loss.append(loss.item())
        test_loss = np.mean(test_loss)

        # Save losses
        train_losses[it] = train_loss
        test_losses[it] = test_loss
        
        early_stopping(test_loss,model,it)
        if early_stopping.early_stop:
            print('Patience Exhausted')
            break

        dt = datetime.now() - t0
        print(dt)
        print(f'Epoch {it+1}/{epochs}, Train Loss: {train_loss:.4f}, \
          Validation Loss: {test_loss:.4f}, Duration: {dt}, Best Val Epoch: {early_stopping.best_test_epoch}')

    return train_losses, test_losses

In [30]:
train_losses, val_losses = batch_gd(model, criterion, optimizer, 
                                    train_loader, val_loader, epochs=20)

  5%|██                                      | 1/20 [25:37<8:06:44, 1537.10s/it]

0:25:37.096070
Epoch 1/20, Train Loss: 0.7717,           Validation Loss: 1.0817, Duration: 0:25:37.096070, Best Val Epoch: 0


 10%|████                                    | 2/20 [52:39<7:56:13, 1587.43s/it]

0:27:02.644952
Epoch 2/20, Train Loss: 0.7045,           Validation Loss: 1.0807, Duration: 0:27:02.644952, Best Val Epoch: 1


 15%|█████▋                                | 3/20 [1:19:56<7:36:10, 1610.06s/it]

0:27:16.958219
Epoch 3/20, Train Loss: 0.6828,           Validation Loss: 1.0849, Duration: 0:27:16.958219, Best Val Epoch: 1


 20%|███████▌                              | 4/20 [1:47:17<7:12:34, 1622.18s/it]

0:27:20.759373
Epoch 4/20, Train Loss: 0.6708,           Validation Loss: 1.1106, Duration: 0:27:20.759373, Best Val Epoch: 1


 25%|█████████▌                            | 5/20 [2:14:39<6:47:20, 1629.38s/it]

0:27:22.119368
Epoch 5/20, Train Loss: 0.6611,           Validation Loss: 1.0849, Duration: 0:27:22.119368, Best Val Epoch: 1


 30%|███████████▍                          | 6/20 [2:41:54<6:20:37, 1631.25s/it]

0:27:14.880724
Epoch 6/20, Train Loss: 0.6527,           Validation Loss: 1.1037, Duration: 0:27:14.880724, Best Val Epoch: 1


 35%|█████████████▎                        | 7/20 [3:09:12<5:53:56, 1633.55s/it]

0:27:18.272007
Epoch 7/20, Train Loss: 0.6459,           Validation Loss: 1.0370, Duration: 0:27:18.272007, Best Val Epoch: 6


 40%|███████████████▏                      | 8/20 [3:36:33<5:27:08, 1635.72s/it]

0:27:20.358931
Epoch 8/20, Train Loss: 0.6435,           Validation Loss: 1.0945, Duration: 0:27:20.358931, Best Val Epoch: 6


 45%|█████████████████                     | 9/20 [4:03:53<5:00:07, 1637.06s/it]

0:27:19.993133
Epoch 9/20, Train Loss: 0.6397,           Validation Loss: 1.0237, Duration: 0:27:19.993133, Best Val Epoch: 8


 50%|██████████████████▌                  | 10/20 [4:31:19<4:33:19, 1639.96s/it]

0:27:26.423472
Epoch 10/20, Train Loss: 0.6380,           Validation Loss: 1.0028, Duration: 0:27:26.423472, Best Val Epoch: 9


 55%|████████████████████▎                | 11/20 [4:58:40<4:06:03, 1640.37s/it]

0:27:21.288795
Epoch 11/20, Train Loss: 0.6344,           Validation Loss: 1.0231, Duration: 0:27:21.288795, Best Val Epoch: 9


 60%|██████████████████████▏              | 12/20 [5:26:06<3:38:55, 1641.88s/it]

0:27:25.238232
Epoch 12/20, Train Loss: 0.6317,           Validation Loss: 1.0862, Duration: 0:27:25.238232, Best Val Epoch: 9


 65%|████████████████████████             | 13/20 [5:53:21<3:11:19, 1639.94s/it]

0:27:15.471926
Epoch 13/20, Train Loss: 0.6269,           Validation Loss: 1.0457, Duration: 0:27:15.471926, Best Val Epoch: 9


 70%|█████████████████████████▉           | 14/20 [6:20:45<2:44:06, 1641.06s/it]

0:27:23.637765
Epoch 14/20, Train Loss: 0.6268,           Validation Loss: 1.0177, Duration: 0:27:23.637765, Best Val Epoch: 9


 75%|███████████████████████████▊         | 15/20 [6:48:03<2:16:40, 1640.18s/it]

0:27:18.117976
Epoch 15/20, Train Loss: 0.6248,           Validation Loss: 1.0493, Duration: 0:27:18.117976, Best Val Epoch: 9


 80%|█████████████████████████████▌       | 16/20 [7:15:23<1:49:20, 1640.00s/it]

0:27:19.584215
Epoch 16/20, Train Loss: 0.6242,           Validation Loss: 1.0216, Duration: 0:27:19.584215, Best Val Epoch: 9


 80%|█████████████████████████████▌       | 16/20 [7:42:35<1:55:38, 1734.73s/it]

Patience Exhausted


In [31]:
n_correct = 0.
n_total = 0.
all_targets = []
all_predictions = []

for inputs, targets in test_loader:
    # Move to GPU
    model.eval()
    inputs, targets = inputs.to(device, dtype=torch.float), targets.to(device, dtype=torch.int64)

    # Forward pass
    outputs = model(inputs)
    
    # Get prediction
    # torch.max returns both max and argmax
    _, predictions = torch.max(outputs, 1)

    # update counts
    n_correct += (predictions == targets).sum().item()
    n_total += targets.shape[0]

    all_targets.append(targets.cpu().numpy())
    all_predictions.append(predictions.cpu().numpy())

test_acc = n_correct / n_total
print(f"Test acc: {test_acc:.4f}")

all_targets = np.concatenate(all_targets)    
all_predictions = np.concatenate(all_predictions)   

Test acc: 0.5823


In [32]:
print('accuracy_score:', accuracy_score(all_targets, all_predictions))
print(classification_report(all_targets, all_predictions, digits=4))

accuracy_score: 0.582293491920211
              precision    recall  f1-score   support

           0     0.1730    0.4108    0.2435     22858
           1     0.8829    0.6081    0.7202    240272
           2     0.1434    0.4644    0.2191     19365

    accuracy                         0.5823    282495
   macro avg     0.3998    0.4944    0.3943    282495
weighted avg     0.7748    0.5823    0.6473    282495



In [33]:
torch.save(model.state_dict(), '/Users/jandh/Desktop/Old Desktop/od/1 quater/Project Lab/model_oversampled.pt')

In [34]:
model.load_state_dict(torch.load('/Users/jandh/Desktop/Old Desktop/od/1 quater/Project Lab/fast-alphas/best_val_roLOB_oversampled.pt', map_location=mps_device))

/var/folders/vf/gw1t6f4j3mv84kp8kpw4j_bw0000gn/T/ipykernel_57021/1991610670.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('/Users/jand

<All keys matched successfully>

In [35]:
n_correct = 0.
n_total = 0.
all_targets = []
all_predictions = []

for inputs, targets in test_loader:
    # Move to GPU
    model.eval()
    inputs, targets = inputs.to(device, dtype=torch.float), targets.to(device, dtype=torch.int64)

    # Forward pass
    outputs = model(inputs)
    
    # Get prediction
    # torch.max returns both max and argmax
    _, predictions = torch.max(outputs, 1)

    # update counts
    n_correct += (predictions == targets).sum().item()
    n_total += targets.shape[0]

    all_targets.append(targets.cpu().numpy())
    all_predictions.append(predictions.cpu().numpy())

test_acc = n_correct / n_total
print(f"Test acc: {test_acc:.4f}")

all_targets = np.concatenate(all_targets)    
all_predictions = np.concatenate(all_predictions)   

Test acc: 0.5360


In [36]:
print('accuracy_score:', accuracy_score(all_targets, all_predictions))
print(classification_report(all_targets, all_predictions, digits=4))

accuracy_score: 0.5359988672365883
              precision    recall  f1-score   support

           0     0.1610    0.4797    0.2411     22858
           1     0.8883    0.5414    0.6728    240272
           2     0.1526    0.5352    0.2375     19365

    accuracy                         0.5360    282495
   macro avg     0.4006    0.5188    0.3838    282495
weighted avg     0.7790    0.5360    0.6080    282495

